### PR TITLE
[Fixes #749] Integrate OCA app in geonode madagascar

### PR DESCRIPTION
**Pull request by abulojoshua1**
Integrate OCA Django app

#### What does the PR do
- Integrates a new OCA Django app

#### Changes Made
- Added the OCA app with all it's static files
- I renamed `mad_geonode/templates/site_index.html` to `mad_geonode/templates/site_index_renamed.html`
- Updated `mad_geonode/url.py` to point the site index to the `HomePage` view from `oca.views.HomePage`

### CODE REVIEW

**Comment by giohappy** [comment]
@abulojoshua1 some changes needed:

- the app should leave in a separate page, which will be reached from header link
- the app shouldn't appear on the home page. The home page must be the original one from GeoNode

**Comment by abulojoshua1** [comment]
> @abulojoshua1 some changes needed:
> 
> * the app should leave in a separate page, which will be reached from header link
> * the app shouldn't appear on the home page. The home page must be the original one from GeoNode

@giohappy, I have pushed some new changes that implement the feedback.

**Comment by afabiani** [comment]
@giohappy it looks ok to me

**Comment by giohappy** [comment]
@abulojoshua1 can you pass me the two following screenshots?

 - home page of their geonode, with the OCA link in the header
 - OCA app page

I will share it with them to ask if it's fine and if they want to enable the app right away.

**Comment by abulojoshua1** [comment]
@giohappy, here are the screenshots:
- The OCA app page
Screenshot 2020-07-20 at 16 09 35

Screenshot 2020-07-20 at 16 08 56
- The home page
Screenshot 2020-07-20 at 16 08 42

**Comment by giohappy** [comment]
@afabiani please go on with the merge and update the online instance with OCA integrated.

**Comment by afabiani** [comment]
Done

**Pull request merged**
